### PR TITLE
RHMAP-2594 Update fh sdk to 2.5.0

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by wei-lee** [comment]
looks good

**Comment by danielpassos** [comment]
I'm not sure if we need `httpclient-4.3.6.jar`

**Comment by wei-lee** [comment]
let me quickly try it to confirm

**Comment by wei-lee** [comment]
Just tried on an Android 4.4 device, the app runs fine without the httpclient jar file. So it can be removed.

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
