### PR TITLE
Fix FH-2657 - Welcome Project Android Gradle is killed if providing newline as an input

### PR DESCRIPTION
**Pull request by leathersole**

### CODE REVIEW

**Comment by danielpassos** [comment]
@leathersole Do you have this fix deployed in somewhere?

**Comment by leathersole** [comment]
Sorry for my careless mistake.
I tested with RHMAP 3.10 welcome android template and overlooked a difference between master and 3.10.
If you kindly tell me how to test this template on Android , I'll do it before sending PR.

**Comment by danielpassos** [comment]
np at all. I'll deploy that in some RHMAP instance and test

**Comment by secondsun** [comment]
@danielpassos Ever get it tested?

**Comment by mmurphy** [comment]
@danielpassos @secondsun hi guys, would this still be useful to include? Does @leathersole have to do anything to get it included?

**Comment by danielpassos** [comment]
@leathersole I'm sorry to not look into this one again. @mmurphy I'm going to test it again and merge

**Comment by mmurphy** [comment]
@danielpassos Thanks

**Comment by secondsun** [comment]
I'm going to close this because the template is deprecated and we haven't merged the PR in quite a while.

**Pull request closed without merging**
